spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo_hibernate_db
    username: root
    password: RadiceRadicata1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create
  output:
    ansi:
      enabled: always
  logging:
    file:
      path: myCustomLog
    level:
      root: info
      esercizi:
        Logging1:
          services: debug



  environment: dev
  var1: 2
  var2: 8